// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/magiclink/services (interfaces: MagicLinkService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_magiclink_service.go -package=mocks github.com/bete7512/goauth/internal/modules/magiclink/services MagicLinkService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/bete7512/goauth/internal/modules/core/handlers/dto"
	dto0 "github.com/bete7512/goauth/internal/modules/magiclink/handlers/dto"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockMagicLinkService is a mock of MagicLinkService interface.
type MockMagicLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockMagicLinkServiceMockRecorder
	isgomock struct{}
}

// MockMagicLinkServiceMockRecorder is the mock recorder for MockMagicLinkService.
type MockMagicLinkServiceMockRecorder struct {
	mock *MockMagicLinkService
}

// NewMockMagicLinkService creates a new mock instance.
func NewMockMagicLinkService(ctrl *gomock.Controller) *MockMagicLinkService {
	mock := &MockMagicLinkService{ctrl: ctrl}
	mock.recorder = &MockMagicLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMagicLinkService) EXPECT() *MockMagicLinkServiceMockRecorder {
	return m.recorder
}

// ResendMagicLink mocks base method.
func (m *MockMagicLinkService) ResendMagicLink(ctx context.Context, req *dto0.MagicLinkSendRequest) (*dto.MessageResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendMagicLink", ctx, req)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// ResendMagicLink indicates an expected call of ResendMagicLink.
func (mr *MockMagicLinkServiceMockRecorder) ResendMagicLink(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendMagicLink", reflect.TypeOf((*MockMagicLinkService)(nil).ResendMagicLink), ctx, req)
}

// SendMagicLink mocks base method.
func (m *MockMagicLinkService) SendMagicLink(ctx context.Context, req *dto0.MagicLinkSendRequest) (*dto.MessageResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMagicLink", ctx, req)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// SendMagicLink indicates an expected call of SendMagicLink.
func (mr *MockMagicLinkServiceMockRecorder) SendMagicLink(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMagicLink", reflect.TypeOf((*MockMagicLinkService)(nil).SendMagicLink), ctx, req)
}

// VerifyByCode mocks base method.
func (m *MockMagicLinkService) VerifyByCode(ctx context.Context, req *dto0.MagicLinkVerifyByCodeRequest) (*dto.AuthResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyByCode", ctx, req)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// VerifyByCode indicates an expected call of VerifyByCode.
func (mr *MockMagicLinkServiceMockRecorder) VerifyByCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyByCode", reflect.TypeOf((*MockMagicLinkService)(nil).VerifyByCode), ctx, req)
}

// VerifyMagicLink mocks base method.
func (m *MockMagicLinkService) VerifyMagicLink(ctx context.Context, token string) (*dto.AuthResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyMagicLink", ctx, token)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// VerifyMagicLink indicates an expected call of VerifyMagicLink.
func (mr *MockMagicLinkServiceMockRecorder) VerifyMagicLink(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyMagicLink", reflect.TypeOf((*MockMagicLinkService)(nil).VerifyMagicLink), ctx, token)
}
