// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/models (interfaces: AuditLogRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_auditlog_repository.go -package=mocks github.com/bete7512/goauth/pkg/models AuditLogRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogRepository) Create(ctx context.Context, log *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepositoryMockRecorder) Create(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepository)(nil).Create), ctx, log)
}

// DeleteByActionOlderThan mocks base method.
func (m *MockAuditLogRepository) DeleteByActionOlderThan(ctx context.Context, action string, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByActionOlderThan", ctx, action, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByActionOlderThan indicates an expected call of DeleteByActionOlderThan.
func (mr *MockAuditLogRepositoryMockRecorder) DeleteByActionOlderThan(ctx, action, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByActionOlderThan", reflect.TypeOf((*MockAuditLogRepository)(nil).DeleteByActionOlderThan), ctx, action, before)
}

// DeleteOlderThan mocks base method.
func (m *MockAuditLogRepository) DeleteOlderThan(ctx context.Context, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockAuditLogRepositoryMockRecorder) DeleteOlderThan(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockAuditLogRepository)(nil).DeleteOlderThan), ctx, before)
}

// FindByAction mocks base method.
func (m *MockAuditLogRepository) FindByAction(ctx context.Context, action string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAction", ctx, action, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByAction indicates an expected call of FindByAction.
func (mr *MockAuditLogRepositoryMockRecorder) FindByAction(ctx, action, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAction", reflect.TypeOf((*MockAuditLogRepository)(nil).FindByAction), ctx, action, opts)
}

// FindByActorID mocks base method.
func (m *MockAuditLogRepository) FindByActorID(ctx context.Context, actorID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActorID", ctx, actorID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByActorID indicates an expected call of FindByActorID.
func (mr *MockAuditLogRepositoryMockRecorder) FindByActorID(ctx, actorID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActorID", reflect.TypeOf((*MockAuditLogRepository)(nil).FindByActorID), ctx, actorID, opts)
}

// FindByOrganizationID mocks base method.
func (m *MockAuditLogRepository) FindByOrganizationID(ctx context.Context, orgID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizationID", ctx, orgID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByOrganizationID indicates an expected call of FindByOrganizationID.
func (mr *MockAuditLogRepositoryMockRecorder) FindByOrganizationID(ctx, orgID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizationID", reflect.TypeOf((*MockAuditLogRepository)(nil).FindByOrganizationID), ctx, orgID, opts)
}

// FindBySeverity mocks base method.
func (m *MockAuditLogRepository) FindBySeverity(ctx context.Context, severity string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySeverity", ctx, severity, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBySeverity indicates an expected call of FindBySeverity.
func (mr *MockAuditLogRepositoryMockRecorder) FindBySeverity(ctx, severity, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySeverity", reflect.TypeOf((*MockAuditLogRepository)(nil).FindBySeverity), ctx, severity, opts)
}

// FindByTargetID mocks base method.
func (m *MockAuditLogRepository) FindByTargetID(ctx context.Context, targetID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTargetID", ctx, targetID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByTargetID indicates an expected call of FindByTargetID.
func (mr *MockAuditLogRepositoryMockRecorder) FindByTargetID(ctx, targetID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTargetID", reflect.TypeOf((*MockAuditLogRepository)(nil).FindByTargetID), ctx, targetID, opts)
}

// List mocks base method.
func (m *MockAuditLogRepository) List(ctx context.Context, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAuditLogRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditLogRepository)(nil).List), ctx, opts)
}
