// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/models (interfaces: InvitationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_invitation_repository.go -package=mocks github.com/bete7512/goauth/pkg/models InvitationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInvitationRepository is a mock of InvitationRepository interface.
type MockInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockInvitationRepositoryMockRecorder is the mock recorder for MockInvitationRepository.
type MockInvitationRepositoryMockRecorder struct {
	mock *MockInvitationRepository
}

// NewMockInvitationRepository creates a new mock instance.
func NewMockInvitationRepository(ctrl *gomock.Controller) *MockInvitationRepository {
	mock := &MockInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationRepository) EXPECT() *MockInvitationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvitationRepository) Create(ctx context.Context, invitation *models.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvitationRepositoryMockRecorder) Create(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockInvitationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvitationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvitationRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockInvitationRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockInvitationRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockInvitationRepository)(nil).DeleteExpired), ctx)
}

// FindByID mocks base method.
func (m *MockInvitationRepository) FindByID(ctx context.Context, id string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvitationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvitationRepository)(nil).FindByID), ctx, id)
}

// FindByToken mocks base method.
func (m *MockInvitationRepository) FindByToken(ctx context.Context, token string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockInvitationRepositoryMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockInvitationRepository)(nil).FindByToken), ctx, token)
}

// FindPendingByEmail mocks base method.
func (m *MockInvitationRepository) FindPendingByEmail(ctx context.Context, email, purpose string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingByEmail", ctx, email, purpose)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingByEmail indicates an expected call of FindPendingByEmail.
func (mr *MockInvitationRepositoryMockRecorder) FindPendingByEmail(ctx, email, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingByEmail", reflect.TypeOf((*MockInvitationRepository)(nil).FindPendingByEmail), ctx, email, purpose)
}

// ListByInviter mocks base method.
func (m *MockInvitationRepository) ListByInviter(ctx context.Context, inviterID string, opts models.InvitationListOpts) ([]*models.Invitation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByInviter", ctx, inviterID, opts)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByInviter indicates an expected call of ListByInviter.
func (mr *MockInvitationRepositoryMockRecorder) ListByInviter(ctx, inviterID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByInviter", reflect.TypeOf((*MockInvitationRepository)(nil).ListByInviter), ctx, inviterID, opts)
}

// ListPendingByEmail mocks base method.
func (m *MockInvitationRepository) ListPendingByEmail(ctx context.Context, email string) ([]*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByEmail", ctx, email)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByEmail indicates an expected call of ListPendingByEmail.
func (mr *MockInvitationRepositoryMockRecorder) ListPendingByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByEmail", reflect.TypeOf((*MockInvitationRepository)(nil).ListPendingByEmail), ctx, email)
}

// Update mocks base method.
func (m *MockInvitationRepository) Update(ctx context.Context, invitation *models.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvitationRepositoryMockRecorder) Update(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvitationRepository)(nil).Update), ctx, invitation)
}
