// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/twofactor/services (interfaces: TwoFactorService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_twofactor_service.go -package=mocks github.com/bete7512/goauth/internal/modules/twofactor/services TwoFactorService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTwoFactorService is a mock of TwoFactorService interface.
type MockTwoFactorService struct {
	ctrl     *gomock.Controller
	recorder *MockTwoFactorServiceMockRecorder
	isgomock struct{}
}

// MockTwoFactorServiceMockRecorder is the mock recorder for MockTwoFactorService.
type MockTwoFactorServiceMockRecorder struct {
	mock *MockTwoFactorService
}

// NewMockTwoFactorService creates a new mock instance.
func NewMockTwoFactorService(ctrl *gomock.Controller) *MockTwoFactorService {
	mock := &MockTwoFactorService{ctrl: ctrl}
	mock.recorder = &MockTwoFactorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwoFactorService) EXPECT() *MockTwoFactorServiceMockRecorder {
	return m.recorder
}

// DisableTwoFactor mocks base method.
func (m *MockTwoFactorService) DisableTwoFactor(ctx context.Context, userID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTwoFactor", ctx, userID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// DisableTwoFactor indicates an expected call of DisableTwoFactor.
func (mr *MockTwoFactorServiceMockRecorder) DisableTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTwoFactor", reflect.TypeOf((*MockTwoFactorService)(nil).DisableTwoFactor), ctx, userID)
}

// EnableTwoFactor mocks base method.
func (m *MockTwoFactorService) EnableTwoFactor(ctx context.Context, userID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTwoFactor", ctx, userID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// EnableTwoFactor indicates an expected call of EnableTwoFactor.
func (mr *MockTwoFactorServiceMockRecorder) EnableTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTwoFactor", reflect.TypeOf((*MockTwoFactorService)(nil).EnableTwoFactor), ctx, userID)
}

// GenerateBackupCodes mocks base method.
func (m *MockTwoFactorService) GenerateBackupCodes(ctx context.Context, userID string) ([]string, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateBackupCodes", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GenerateBackupCodes indicates an expected call of GenerateBackupCodes.
func (mr *MockTwoFactorServiceMockRecorder) GenerateBackupCodes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateBackupCodes", reflect.TypeOf((*MockTwoFactorService)(nil).GenerateBackupCodes), ctx, userID)
}

// GenerateSecret mocks base method.
func (m *MockTwoFactorService) GenerateSecret(ctx context.Context, userEmail string) (string, string, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecret", ctx, userEmail)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GenerateSecret indicates an expected call of GenerateSecret.
func (mr *MockTwoFactorServiceMockRecorder) GenerateSecret(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecret", reflect.TypeOf((*MockTwoFactorService)(nil).GenerateSecret), ctx, userEmail)
}

// GetTwoFactorConfig mocks base method.
func (m *MockTwoFactorService) GetTwoFactorConfig(ctx context.Context, userID string) (*models.TwoFactor, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwoFactorConfig", ctx, userID)
	ret0, _ := ret[0].(*models.TwoFactor)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetTwoFactorConfig indicates an expected call of GetTwoFactorConfig.
func (mr *MockTwoFactorServiceMockRecorder) GetTwoFactorConfig(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwoFactorConfig", reflect.TypeOf((*MockTwoFactorService)(nil).GetTwoFactorConfig), ctx, userID)
}

// GetUser mocks base method.
func (m *MockTwoFactorService) GetUser(ctx context.Context, userID string) (*models.User, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTwoFactorServiceMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTwoFactorService)(nil).GetUser), ctx, userID)
}

// IssueAuthTokenAfter2FA mocks base method.
func (m *MockTwoFactorService) IssueAuthTokenAfter2FA(ctx context.Context, user *models.User, metadata *types.RequestMetadata) (map[string]any, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAuthTokenAfter2FA", ctx, user, metadata)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// IssueAuthTokenAfter2FA indicates an expected call of IssueAuthTokenAfter2FA.
func (mr *MockTwoFactorServiceMockRecorder) IssueAuthTokenAfter2FA(ctx, user, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAuthTokenAfter2FA", reflect.TypeOf((*MockTwoFactorService)(nil).IssueAuthTokenAfter2FA), ctx, user, metadata)
}

// SaveBackupCodes mocks base method.
func (m *MockTwoFactorService) SaveBackupCodes(ctx context.Context, userID string, plainCodes []string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBackupCodes", ctx, userID, plainCodes)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// SaveBackupCodes indicates an expected call of SaveBackupCodes.
func (mr *MockTwoFactorServiceMockRecorder) SaveBackupCodes(ctx, userID, plainCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBackupCodes", reflect.TypeOf((*MockTwoFactorService)(nil).SaveBackupCodes), ctx, userID, plainCodes)
}

// SaveTwoFactorConfig mocks base method.
func (m *MockTwoFactorService) SaveTwoFactorConfig(ctx context.Context, tfConfig *models.TwoFactor) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTwoFactorConfig", ctx, tfConfig)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// SaveTwoFactorConfig indicates an expected call of SaveTwoFactorConfig.
func (mr *MockTwoFactorServiceMockRecorder) SaveTwoFactorConfig(ctx, tfConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTwoFactorConfig", reflect.TypeOf((*MockTwoFactorService)(nil).SaveTwoFactorConfig), ctx, tfConfig)
}

// UseBackupCode mocks base method.
func (m *MockTwoFactorService) UseBackupCode(ctx context.Context, userID, plainCode string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseBackupCode", ctx, userID, plainCode)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// UseBackupCode indicates an expected call of UseBackupCode.
func (mr *MockTwoFactorServiceMockRecorder) UseBackupCode(ctx, userID, plainCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseBackupCode", reflect.TypeOf((*MockTwoFactorService)(nil).UseBackupCode), ctx, userID, plainCode)
}

// VerifyCode mocks base method.
func (m *MockTwoFactorService) VerifyCode(ctx context.Context, userID, code string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, userID, code)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockTwoFactorServiceMockRecorder) VerifyCode(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyCode), ctx, userID, code)
}

// VerifyCodeManual mocks base method.
func (m *MockTwoFactorService) VerifyCodeManual(ctx context.Context, secret, code string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCodeManual", ctx, secret, code)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// VerifyCodeManual indicates an expected call of VerifyCodeManual.
func (mr *MockTwoFactorServiceMockRecorder) VerifyCodeManual(ctx, secret, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCodeManual", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyCodeManual), ctx, secret, code)
}

// VerifyCodeOrBackup mocks base method.
func (m *MockTwoFactorService) VerifyCodeOrBackup(ctx context.Context, userID, code string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCodeOrBackup", ctx, userID, code)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// VerifyCodeOrBackup indicates an expected call of VerifyCodeOrBackup.
func (mr *MockTwoFactorServiceMockRecorder) VerifyCodeOrBackup(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCodeOrBackup", reflect.TypeOf((*MockTwoFactorService)(nil).VerifyCodeOrBackup), ctx, userID, code)
}
