// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/models (interfaces: UserRepository,ExtendedAttributeRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_user_repository.go -package=mocks github.com/bete7512/goauth/pkg/models UserRepository,ExtendedAttributeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByEmailOrUsername mocks base method.
func (m *MockUserRepository) FindByEmailOrUsername(ctx context.Context, emailOrUsername string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailOrUsername", ctx, emailOrUsername)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailOrUsername indicates an expected call of FindByEmailOrUsername.
func (mr *MockUserRepositoryMockRecorder) FindByEmailOrUsername(ctx, emailOrUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailOrUsername", reflect.TypeOf((*MockUserRepository)(nil).FindByEmailOrUsername), ctx, emailOrUsername)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// FindByPhoneNumber mocks base method.
func (m *MockUserRepository) FindByPhoneNumber(ctx context.Context, phoneNumber string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPhoneNumber", ctx, phoneNumber)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPhoneNumber indicates an expected call of FindByPhoneNumber.
func (mr *MockUserRepositoryMockRecorder) FindByPhoneNumber(ctx, phoneNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPhoneNumber", reflect.TypeOf((*MockUserRepository)(nil).FindByPhoneNumber), ctx, phoneNumber)
}

// FindByUsername mocks base method.
func (m *MockUserRepository) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockUserRepositoryMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockUserRepository)(nil).FindByUsername), ctx, username)
}

// IsAvailable mocks base method.
func (m *MockUserRepository) IsAvailable(ctx context.Context, field, value string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable", ctx, field, value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockUserRepositoryMockRecorder) IsAvailable(ctx, field, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockUserRepository)(nil).IsAvailable), ctx, field, value)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, opts models.UserListOpts) ([]*models.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// MockExtendedAttributeRepository is a mock of ExtendedAttributeRepository interface.
type MockExtendedAttributeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExtendedAttributeRepositoryMockRecorder
	isgomock struct{}
}

// MockExtendedAttributeRepositoryMockRecorder is the mock recorder for MockExtendedAttributeRepository.
type MockExtendedAttributeRepositoryMockRecorder struct {
	mock *MockExtendedAttributeRepository
}

// NewMockExtendedAttributeRepository creates a new mock instance.
func NewMockExtendedAttributeRepository(ctrl *gomock.Controller) *MockExtendedAttributeRepository {
	mock := &MockExtendedAttributeRepository{ctrl: ctrl}
	mock.recorder = &MockExtendedAttributeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtendedAttributeRepository) EXPECT() *MockExtendedAttributeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExtendedAttributeRepository) Create(ctx context.Context, attr *models.ExtendedAttributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExtendedAttributeRepositoryMockRecorder) Create(ctx, attr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).Create), ctx, attr)
}

// Delete mocks base method.
func (m *MockExtendedAttributeRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExtendedAttributeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).Delete), ctx, id)
}

// FindByNameAndValue mocks base method.
func (m *MockExtendedAttributeRepository) FindByNameAndValue(ctx context.Context, name, value string) (*models.ExtendedAttributes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNameAndValue", ctx, name, value)
	ret0, _ := ret[0].(*models.ExtendedAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNameAndValue indicates an expected call of FindByNameAndValue.
func (mr *MockExtendedAttributeRepositoryMockRecorder) FindByNameAndValue(ctx, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNameAndValue", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).FindByNameAndValue), ctx, name, value)
}

// FindByUserAndName mocks base method.
func (m *MockExtendedAttributeRepository) FindByUserAndName(ctx context.Context, userID, name string) (*models.ExtendedAttributes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndName", ctx, userID, name)
	ret0, _ := ret[0].(*models.ExtendedAttributes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndName indicates an expected call of FindByUserAndName.
func (mr *MockExtendedAttributeRepositoryMockRecorder) FindByUserAndName(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndName", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).FindByUserAndName), ctx, userID, name)
}

// Upsert mocks base method.
func (m *MockExtendedAttributeRepository) Upsert(ctx context.Context, userID, name, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, userID, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockExtendedAttributeRepositoryMockRecorder) Upsert(ctx, userID, name, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).Upsert), ctx, userID, name, value)
}

// UpsertMany mocks base method.
func (m *MockExtendedAttributeRepository) UpsertMany(ctx context.Context, attrs []models.ExtendedAttributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMany", ctx, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMany indicates an expected call of UpsertMany.
func (mr *MockExtendedAttributeRepositoryMockRecorder) UpsertMany(ctx, attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMany", reflect.TypeOf((*MockExtendedAttributeRepository)(nil).UpsertMany), ctx, attrs)
}
