// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/notification/services (interfaces: NotificationService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_notification_service.go -package=mocks github.com/bete7512/goauth/internal/modules/notification/services NotificationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/internal/modules/notification/models"
	models0 "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendCustomEmail mocks base method.
func (m *MockNotificationService) SendCustomEmail(ctx context.Context, message *models.EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCustomEmail", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCustomEmail indicates an expected call of SendCustomEmail.
func (mr *MockNotificationServiceMockRecorder) SendCustomEmail(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCustomEmail", reflect.TypeOf((*MockNotificationService)(nil).SendCustomEmail), ctx, message)
}

// SendCustomSMS mocks base method.
func (m *MockNotificationService) SendCustomSMS(ctx context.Context, message *models.SMSMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCustomSMS", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCustomSMS indicates an expected call of SendCustomSMS.
func (mr *MockNotificationServiceMockRecorder) SendCustomSMS(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCustomSMS", reflect.TypeOf((*MockNotificationService)(nil).SendCustomSMS), ctx, message)
}

// SendEmailVerification mocks base method.
func (m *MockNotificationService) SendEmailVerification(ctx context.Context, email, userName, verificationLink string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerification", ctx, email, userName, verificationLink)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailVerification indicates an expected call of SendEmailVerification.
func (mr *MockNotificationServiceMockRecorder) SendEmailVerification(ctx, email, userName, verificationLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerification", reflect.TypeOf((*MockNotificationService)(nil).SendEmailVerification), ctx, email, userName, verificationLink)
}

// SendLoginAlert mocks base method.
func (m *MockNotificationService) SendLoginAlert(ctx context.Context, user models0.User, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLoginAlert", ctx, user, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLoginAlert indicates an expected call of SendLoginAlert.
func (mr *MockNotificationServiceMockRecorder) SendLoginAlert(ctx, user, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLoginAlert", reflect.TypeOf((*MockNotificationService)(nil).SendLoginAlert), ctx, user, metadata)
}

// SendMagicLinkEmail mocks base method.
func (m *MockNotificationService) SendMagicLinkEmail(ctx context.Context, email, userName, magicLink, code, expiryTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMagicLinkEmail", ctx, email, userName, magicLink, code, expiryTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMagicLinkEmail indicates an expected call of SendMagicLinkEmail.
func (mr *MockNotificationServiceMockRecorder) SendMagicLinkEmail(ctx, email, userName, magicLink, code, expiryTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMagicLinkEmail", reflect.TypeOf((*MockNotificationService)(nil).SendMagicLinkEmail), ctx, email, userName, magicLink, code, expiryTime)
}

// SendPasswordChangedAlert mocks base method.
func (m *MockNotificationService) SendPasswordChangedAlert(ctx context.Context, user models0.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordChangedAlert", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordChangedAlert indicates an expected call of SendPasswordChangedAlert.
func (mr *MockNotificationServiceMockRecorder) SendPasswordChangedAlert(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordChangedAlert", reflect.TypeOf((*MockNotificationService)(nil).SendPasswordChangedAlert), ctx, user)
}

// SendPasswordResetEmail mocks base method.
func (m *MockNotificationService) SendPasswordResetEmail(ctx context.Context, email, userName, resetLink, code, expiryTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", ctx, email, userName, resetLink, code, expiryTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetEmail indicates an expected call of SendPasswordResetEmail.
func (mr *MockNotificationServiceMockRecorder) SendPasswordResetEmail(ctx, email, userName, resetLink, code, expiryTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockNotificationService)(nil).SendPasswordResetEmail), ctx, email, userName, resetLink, code, expiryTime)
}

// SendPasswordResetSMS mocks base method.
func (m *MockNotificationService) SendPasswordResetSMS(ctx context.Context, phoneNumber, code, expiryTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetSMS", ctx, phoneNumber, code, expiryTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetSMS indicates an expected call of SendPasswordResetSMS.
func (mr *MockNotificationServiceMockRecorder) SendPasswordResetSMS(ctx, phoneNumber, code, expiryTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetSMS", reflect.TypeOf((*MockNotificationService)(nil).SendPasswordResetSMS), ctx, phoneNumber, code, expiryTime)
}

// SendPhoneVerification mocks base method.
func (m *MockNotificationService) SendPhoneVerification(ctx context.Context, phoneNumber, userName, code, expiryTime string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPhoneVerification", ctx, phoneNumber, userName, code, expiryTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPhoneVerification indicates an expected call of SendPhoneVerification.
func (mr *MockNotificationServiceMockRecorder) SendPhoneVerification(ctx, phoneNumber, userName, code, expiryTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPhoneVerification", reflect.TypeOf((*MockNotificationService)(nil).SendPhoneVerification), ctx, phoneNumber, userName, code, expiryTime)
}

// SendWelcomeEmail mocks base method.
func (m *MockNotificationService) SendWelcomeEmail(ctx context.Context, user models0.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWelcomeEmail", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWelcomeEmail indicates an expected call of SendWelcomeEmail.
func (mr *MockNotificationServiceMockRecorder) SendWelcomeEmail(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWelcomeEmail", reflect.TypeOf((*MockNotificationService)(nil).SendWelcomeEmail), ctx, user)
}
