// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/types (interfaces: Storage,CoreStorage,SessionStorage,StatelessStorage,AdminStorage,OAuthStorage,TwoFactorStorage)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_storage.go -package=mocks github.com/bete7512/goauth/pkg/types Storage,CoreStorage,SessionStorage,StatelessStorage,AdminStorage,OAuthStorage,TwoFactorStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Admin mocks base method.
func (m *MockStorage) Admin() types.AdminStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admin")
	ret0, _ := ret[0].(types.AdminStorage)
	return ret0
}

// Admin indicates an expected call of Admin.
func (mr *MockStorageMockRecorder) Admin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admin", reflect.TypeOf((*MockStorage)(nil).Admin))
}

// AuditLog mocks base method.
func (m *MockStorage) AuditLog() types.AuditLogStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuditLog")
	ret0, _ := ret[0].(types.AuditLogStorage)
	return ret0
}

// AuditLog indicates an expected call of AuditLog.
func (mr *MockStorageMockRecorder) AuditLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuditLog", reflect.TypeOf((*MockStorage)(nil).AuditLog))
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// Core mocks base method.
func (m *MockStorage) Core() types.CoreStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Core")
	ret0, _ := ret[0].(types.CoreStorage)
	return ret0
}

// Core indicates an expected call of Core.
func (mr *MockStorageMockRecorder) Core() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Core", reflect.TypeOf((*MockStorage)(nil).Core))
}

// DB mocks base method.
func (m *MockStorage) DB() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(any)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockStorageMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockStorage)(nil).DB))
}

// Migrate mocks base method.
func (m *MockStorage) Migrate(ctx context.Context, arg1 []any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockStorageMockRecorder) Migrate(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockStorage)(nil).Migrate), ctx, arg1)
}

// OAuth mocks base method.
func (m *MockStorage) OAuth() types.OAuthStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuth")
	ret0, _ := ret[0].(types.OAuthStorage)
	return ret0
}

// OAuth indicates an expected call of OAuth.
func (mr *MockStorageMockRecorder) OAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuth", reflect.TypeOf((*MockStorage)(nil).OAuth))
}

// Session mocks base method.
func (m *MockStorage) Session() types.SessionStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Session")
	ret0, _ := ret[0].(types.SessionStorage)
	return ret0
}

// Session indicates an expected call of Session.
func (mr *MockStorageMockRecorder) Session() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Session", reflect.TypeOf((*MockStorage)(nil).Session))
}

// Stateless mocks base method.
func (m *MockStorage) Stateless() types.StatelessStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stateless")
	ret0, _ := ret[0].(types.StatelessStorage)
	return ret0
}

// Stateless indicates an expected call of Stateless.
func (mr *MockStorageMockRecorder) Stateless() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stateless", reflect.TypeOf((*MockStorage)(nil).Stateless))
}

// TwoFactorAuth mocks base method.
func (m *MockStorage) TwoFactorAuth() types.TwoFactorStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TwoFactorAuth")
	ret0, _ := ret[0].(types.TwoFactorStorage)
	return ret0
}

// TwoFactorAuth indicates an expected call of TwoFactorAuth.
func (mr *MockStorageMockRecorder) TwoFactorAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TwoFactorAuth", reflect.TypeOf((*MockStorage)(nil).TwoFactorAuth))
}

// MockCoreStorage is a mock of CoreStorage interface.
type MockCoreStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCoreStorageMockRecorder
	isgomock struct{}
}

// MockCoreStorageMockRecorder is the mock recorder for MockCoreStorage.
type MockCoreStorageMockRecorder struct {
	mock *MockCoreStorage
}

// NewMockCoreStorage creates a new mock instance.
func NewMockCoreStorage(ctrl *gomock.Controller) *MockCoreStorage {
	mock := &MockCoreStorage{ctrl: ctrl}
	mock.recorder = &MockCoreStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreStorage) EXPECT() *MockCoreStorageMockRecorder {
	return m.recorder
}

// ExtendedAttributes mocks base method.
func (m *MockCoreStorage) ExtendedAttributes() models.ExtendedAttributeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendedAttributes")
	ret0, _ := ret[0].(models.ExtendedAttributeRepository)
	return ret0
}

// ExtendedAttributes indicates an expected call of ExtendedAttributes.
func (mr *MockCoreStorageMockRecorder) ExtendedAttributes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendedAttributes", reflect.TypeOf((*MockCoreStorage)(nil).ExtendedAttributes))
}

// Tokens mocks base method.
func (m *MockCoreStorage) Tokens() models.TokenRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tokens")
	ret0, _ := ret[0].(models.TokenRepository)
	return ret0
}

// Tokens indicates an expected call of Tokens.
func (mr *MockCoreStorageMockRecorder) Tokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tokens", reflect.TypeOf((*MockCoreStorage)(nil).Tokens))
}

// Users mocks base method.
func (m *MockCoreStorage) Users() models.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(models.UserRepository)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockCoreStorageMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockCoreStorage)(nil).Users))
}

// WithTransaction mocks base method.
func (m *MockCoreStorage) WithTransaction(ctx context.Context, fn func(types.CoreStorage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockCoreStorageMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockCoreStorage)(nil).WithTransaction), ctx, fn)
}

// MockSessionStorage is a mock of SessionStorage interface.
type MockSessionStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStorageMockRecorder
	isgomock struct{}
}

// MockSessionStorageMockRecorder is the mock recorder for MockSessionStorage.
type MockSessionStorageMockRecorder struct {
	mock *MockSessionStorage
}

// NewMockSessionStorage creates a new mock instance.
func NewMockSessionStorage(ctrl *gomock.Controller) *MockSessionStorage {
	mock := &MockSessionStorage{ctrl: ctrl}
	mock.recorder = &MockSessionStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStorage) EXPECT() *MockSessionStorageMockRecorder {
	return m.recorder
}

// Sessions mocks base method.
func (m *MockSessionStorage) Sessions() models.SessionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions")
	ret0, _ := ret[0].(models.SessionRepository)
	return ret0
}

// Sessions indicates an expected call of Sessions.
func (mr *MockSessionStorageMockRecorder) Sessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockSessionStorage)(nil).Sessions))
}

// WithTransaction mocks base method.
func (m *MockSessionStorage) WithTransaction(ctx context.Context, fn func(types.SessionStorage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockSessionStorageMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockSessionStorage)(nil).WithTransaction), ctx, fn)
}

// MockStatelessStorage is a mock of StatelessStorage interface.
type MockStatelessStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStatelessStorageMockRecorder
	isgomock struct{}
}

// MockStatelessStorageMockRecorder is the mock recorder for MockStatelessStorage.
type MockStatelessStorageMockRecorder struct {
	mock *MockStatelessStorage
}

// NewMockStatelessStorage creates a new mock instance.
func NewMockStatelessStorage(ctrl *gomock.Controller) *MockStatelessStorage {
	mock := &MockStatelessStorage{ctrl: ctrl}
	mock.recorder = &MockStatelessStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatelessStorage) EXPECT() *MockStatelessStorageMockRecorder {
	return m.recorder
}

// Blacklist mocks base method.
func (m *MockStatelessStorage) Blacklist() models.BlacklistRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blacklist")
	ret0, _ := ret[0].(models.BlacklistRepository)
	return ret0
}

// Blacklist indicates an expected call of Blacklist.
func (mr *MockStatelessStorageMockRecorder) Blacklist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blacklist", reflect.TypeOf((*MockStatelessStorage)(nil).Blacklist))
}

// MockAdminStorage is a mock of AdminStorage interface.
type MockAdminStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStorageMockRecorder
	isgomock struct{}
}

// MockAdminStorageMockRecorder is the mock recorder for MockAdminStorage.
type MockAdminStorageMockRecorder struct {
	mock *MockAdminStorage
}

// NewMockAdminStorage creates a new mock instance.
func NewMockAdminStorage(ctrl *gomock.Controller) *MockAdminStorage {
	mock := &MockAdminStorage{ctrl: ctrl}
	mock.recorder = &MockAdminStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStorage) EXPECT() *MockAdminStorageMockRecorder {
	return m.recorder
}

// MockOAuthStorage is a mock of OAuthStorage interface.
type MockOAuthStorage struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthStorageMockRecorder
	isgomock struct{}
}

// MockOAuthStorageMockRecorder is the mock recorder for MockOAuthStorage.
type MockOAuthStorageMockRecorder struct {
	mock *MockOAuthStorage
}

// NewMockOAuthStorage creates a new mock instance.
func NewMockOAuthStorage(ctrl *gomock.Controller) *MockOAuthStorage {
	mock := &MockOAuthStorage{ctrl: ctrl}
	mock.recorder = &MockOAuthStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthStorage) EXPECT() *MockOAuthStorageMockRecorder {
	return m.recorder
}

// Accounts mocks base method.
func (m *MockOAuthStorage) Accounts() models.AccountRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accounts")
	ret0, _ := ret[0].(models.AccountRepository)
	return ret0
}

// Accounts indicates an expected call of Accounts.
func (mr *MockOAuthStorageMockRecorder) Accounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accounts", reflect.TypeOf((*MockOAuthStorage)(nil).Accounts))
}

// WithTransaction mocks base method.
func (m *MockOAuthStorage) WithTransaction(ctx context.Context, fn func(types.OAuthStorage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockOAuthStorageMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockOAuthStorage)(nil).WithTransaction), ctx, fn)
}

// MockTwoFactorStorage is a mock of TwoFactorStorage interface.
type MockTwoFactorStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTwoFactorStorageMockRecorder
	isgomock struct{}
}

// MockTwoFactorStorageMockRecorder is the mock recorder for MockTwoFactorStorage.
type MockTwoFactorStorageMockRecorder struct {
	mock *MockTwoFactorStorage
}

// NewMockTwoFactorStorage creates a new mock instance.
func NewMockTwoFactorStorage(ctrl *gomock.Controller) *MockTwoFactorStorage {
	mock := &MockTwoFactorStorage{ctrl: ctrl}
	mock.recorder = &MockTwoFactorStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwoFactorStorage) EXPECT() *MockTwoFactorStorageMockRecorder {
	return m.recorder
}

// BackupCodes mocks base method.
func (m *MockTwoFactorStorage) BackupCodes() models.BackupCodeRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupCodes")
	ret0, _ := ret[0].(models.BackupCodeRepository)
	return ret0
}

// BackupCodes indicates an expected call of BackupCodes.
func (mr *MockTwoFactorStorageMockRecorder) BackupCodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupCodes", reflect.TypeOf((*MockTwoFactorStorage)(nil).BackupCodes))
}

// TwoFactor mocks base method.
func (m *MockTwoFactorStorage) TwoFactor() models.TwoFactorRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TwoFactor")
	ret0, _ := ret[0].(models.TwoFactorRepository)
	return ret0
}

// TwoFactor indicates an expected call of TwoFactor.
func (mr *MockTwoFactorStorageMockRecorder) TwoFactor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TwoFactor", reflect.TypeOf((*MockTwoFactorStorage)(nil).TwoFactor))
}

// WithTransaction mocks base method.
func (m *MockTwoFactorStorage) WithTransaction(ctx context.Context, fn func(types.TwoFactorStorage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTwoFactorStorageMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTwoFactorStorage)(nil).WithTransaction), ctx, fn)
}
