// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/security/cookie (interfaces: CookieEncoder)
//
// Generated by this command:
//
//	mockgen -destination=../../../internal/mocks/mock_cookie_encoder.go -package=mocks github.com/bete7512/goauth/internal/security/cookie CookieEncoder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCookieEncoder is a mock of CookieEncoder interface.
type MockCookieEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockCookieEncoderMockRecorder
	isgomock struct{}
}

// MockCookieEncoderMockRecorder is the mock recorder for MockCookieEncoder.
type MockCookieEncoderMockRecorder struct {
	mock *MockCookieEncoder
}

// NewMockCookieEncoder creates a new mock instance.
func NewMockCookieEncoder(ctrl *gomock.Controller) *MockCookieEncoder {
	mock := &MockCookieEncoder{ctrl: ctrl}
	mock.recorder = &MockCookieEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookieEncoder) EXPECT() *MockCookieEncoderMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockCookieEncoder) Decode(cookieValue string) (*types.SessionCookieData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", cookieValue)
	ret0, _ := ret[0].(*types.SessionCookieData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockCookieEncoderMockRecorder) Decode(cookieValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCookieEncoder)(nil).Decode), cookieValue)
}

// Encode mocks base method.
func (m *MockCookieEncoder) Encode(data *types.SessionCookieData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockCookieEncoderMockRecorder) Encode(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockCookieEncoder)(nil).Encode), data)
}

// EncodingType mocks base method.
func (m *MockCookieEncoder) EncodingType() types.CookieEncoding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodingType")
	ret0, _ := ret[0].(types.CookieEncoding)
	return ret0
}

// EncodingType indicates an expected call of EncodingType.
func (mr *MockCookieEncoderMockRecorder) EncodingType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodingType", reflect.TypeOf((*MockCookieEncoder)(nil).EncodingType))
}

// MaxSize mocks base method.
func (m *MockCookieEncoder) MaxSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxSize indicates an expected call of MaxSize.
func (mr *MockCookieEncoderMockRecorder) MaxSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxSize", reflect.TypeOf((*MockCookieEncoder)(nil).MaxSize))
}
