// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/audit/services (interfaces: AuditService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_audit_service.go -package=mocks github.com/bete7512/goauth/internal/modules/audit/services AuditService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// CleanupOldLogs mocks base method.
func (m *MockAuditService) CleanupOldLogs(ctx context.Context) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldLogs", ctx)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// CleanupOldLogs indicates an expected call of CleanupOldLogs.
func (mr *MockAuditServiceMockRecorder) CleanupOldLogs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldLogs", reflect.TypeOf((*MockAuditService)(nil).CleanupOldLogs), ctx)
}

// CreateAuditLog mocks base method.
func (m *MockAuditService) CreateAuditLog(ctx context.Context, log *models.AuditLog) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, log)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditServiceMockRecorder) CreateAuditLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditService)(nil).CreateAuditLog), ctx, log)
}

// GetAuditLogsByAction mocks base method.
func (m *MockAuditService) GetAuditLogsByAction(ctx context.Context, action string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogsByAction", ctx, action, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetAuditLogsByAction indicates an expected call of GetAuditLogsByAction.
func (mr *MockAuditServiceMockRecorder) GetAuditLogsByAction(ctx, action, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogsByAction", reflect.TypeOf((*MockAuditService)(nil).GetAuditLogsByAction), ctx, action, opts)
}

// GetMyAuditLogs mocks base method.
func (m *MockAuditService) GetMyAuditLogs(ctx context.Context, userID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyAuditLogs", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetMyAuditLogs indicates an expected call of GetMyAuditLogs.
func (mr *MockAuditServiceMockRecorder) GetMyAuditLogs(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyAuditLogs", reflect.TypeOf((*MockAuditService)(nil).GetMyAuditLogs), ctx, userID, opts)
}

// GetMyChanges mocks base method.
func (m *MockAuditService) GetMyChanges(ctx context.Context, userID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyChanges", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetMyChanges indicates an expected call of GetMyChanges.
func (mr *MockAuditServiceMockRecorder) GetMyChanges(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyChanges", reflect.TypeOf((*MockAuditService)(nil).GetMyChanges), ctx, userID, opts)
}

// GetMyLogins mocks base method.
func (m *MockAuditService) GetMyLogins(ctx context.Context, userID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyLogins", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetMyLogins indicates an expected call of GetMyLogins.
func (mr *MockAuditServiceMockRecorder) GetMyLogins(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyLogins", reflect.TypeOf((*MockAuditService)(nil).GetMyLogins), ctx, userID, opts)
}

// GetMySecurity mocks base method.
func (m *MockAuditService) GetMySecurity(ctx context.Context, userID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMySecurity", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetMySecurity indicates an expected call of GetMySecurity.
func (mr *MockAuditServiceMockRecorder) GetMySecurity(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMySecurity", reflect.TypeOf((*MockAuditService)(nil).GetMySecurity), ctx, userID, opts)
}

// GetUserAuditLogs mocks base method.
func (m *MockAuditService) GetUserAuditLogs(ctx context.Context, userID string, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAuditLogs", ctx, userID, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// GetUserAuditLogs indicates an expected call of GetUserAuditLogs.
func (mr *MockAuditServiceMockRecorder) GetUserAuditLogs(ctx, userID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAuditLogs", reflect.TypeOf((*MockAuditService)(nil).GetUserAuditLogs), ctx, userID, opts)
}

// ListAllAuditLogs mocks base method.
func (m *MockAuditService) ListAllAuditLogs(ctx context.Context, opts models.AuditLogListOpts) ([]*models.AuditLog, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllAuditLogs", ctx, opts)
	ret0, _ := ret[0].([]*models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// ListAllAuditLogs indicates an expected call of ListAllAuditLogs.
func (mr *MockAuditServiceMockRecorder) ListAllAuditLogs(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllAuditLogs", reflect.TypeOf((*MockAuditService)(nil).ListAllAuditLogs), ctx, opts)
}
