// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/invitation/services (interfaces: InvitationService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../internal/mocks/mock_platform_invitation_service.go -package=mocks github.com/bete7512/goauth/internal/modules/invitation/services InvitationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/bete7512/goauth/internal/modules/invitation/handlers/dto"
	models "github.com/bete7512/goauth/pkg/models"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockInvitationService is a mock of InvitationService interface.
type MockInvitationService struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationServiceMockRecorder
	isgomock struct{}
}

// MockInvitationServiceMockRecorder is the mock recorder for MockInvitationService.
type MockInvitationServiceMockRecorder struct {
	mock *MockInvitationService
}

// NewMockInvitationService creates a new mock instance.
func NewMockInvitationService(ctrl *gomock.Controller) *MockInvitationService {
	mock := &MockInvitationService{ctrl: ctrl}
	mock.recorder = &MockInvitationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationService) EXPECT() *MockInvitationServiceMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockInvitationService) Accept(ctx context.Context, userID, userEmail, token string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, userID, userEmail, token)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockInvitationServiceMockRecorder) Accept(ctx, userID, userEmail, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockInvitationService)(nil).Accept), ctx, userID, userEmail, token)
}

// Cancel mocks base method.
func (m *MockInvitationService) Cancel(ctx context.Context, invID, inviterID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, invID, inviterID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockInvitationServiceMockRecorder) Cancel(ctx, invID, inviterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockInvitationService)(nil).Cancel), ctx, invID, inviterID)
}

// Decline mocks base method.
func (m *MockInvitationService) Decline(ctx context.Context, userID, token string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", ctx, userID, token)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// Decline indicates an expected call of Decline.
func (mr *MockInvitationServiceMockRecorder) Decline(ctx, userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*MockInvitationService)(nil).Decline), ctx, userID, token)
}

// List mocks base method.
func (m *MockInvitationService) List(ctx context.Context, inviterID string, opts models.InvitationListOpts) ([]*models.Invitation, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, inviterID, opts)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockInvitationServiceMockRecorder) List(ctx, inviterID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvitationService)(nil).List), ctx, inviterID, opts)
}

// ListPendingByEmail mocks base method.
func (m *MockInvitationService) ListPendingByEmail(ctx context.Context, email string) ([]*models.Invitation, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByEmail", ctx, email)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// ListPendingByEmail indicates an expected call of ListPendingByEmail.
func (mr *MockInvitationServiceMockRecorder) ListPendingByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByEmail", reflect.TypeOf((*MockInvitationService)(nil).ListPendingByEmail), ctx, email)
}

// Send mocks base method.
func (m *MockInvitationService) Send(ctx context.Context, req *dto.SendInvitationRequest, inviterID string) (*models.Invitation, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req, inviterID)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockInvitationServiceMockRecorder) Send(ctx, req, inviterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockInvitationService)(nil).Send), ctx, req, inviterID)
}
