// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/models (interfaces: OrganizationRepository,OrganizationMemberRepository,InvitationRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_organization_repository.go -package=mocks github.com/bete7512/goauth/pkg/models OrganizationRepository,OrganizationMemberRepository,InvitationRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationRepository) Create(ctx context.Context, org *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationRepositoryMockRecorder) Create(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationRepository)(nil).Create), ctx, org)
}

// Delete mocks base method.
func (m *MockOrganizationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationRepository)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockOrganizationRepository) FindByID(ctx context.Context, id string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrganizationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrganizationRepository)(nil).FindByID), ctx, id)
}

// FindByOwnerID mocks base method.
func (m *MockOrganizationRepository) FindByOwnerID(ctx context.Context, ownerID string) ([]*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", ctx, ownerID)
	ret0, _ := ret[0].([]*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockOrganizationRepositoryMockRecorder) FindByOwnerID(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockOrganizationRepository)(nil).FindByOwnerID), ctx, ownerID)
}

// FindBySlug mocks base method.
func (m *MockOrganizationRepository) FindBySlug(ctx context.Context, slug string) (*models.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*models.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockOrganizationRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockOrganizationRepository)(nil).FindBySlug), ctx, slug)
}

// IsSlugAvailable mocks base method.
func (m *MockOrganizationRepository) IsSlugAvailable(ctx context.Context, slug string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlugAvailable", ctx, slug)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlugAvailable indicates an expected call of IsSlugAvailable.
func (mr *MockOrganizationRepositoryMockRecorder) IsSlugAvailable(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlugAvailable", reflect.TypeOf((*MockOrganizationRepository)(nil).IsSlugAvailable), ctx, slug)
}

// List mocks base method.
func (m *MockOrganizationRepository) List(ctx context.Context, opts models.OrganizationListOpts) ([]*models.Organization, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].([]*models.Organization)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOrganizationRepositoryMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrganizationRepository)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockOrganizationRepository) Update(ctx context.Context, org *models.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationRepositoryMockRecorder) Update(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationRepository)(nil).Update), ctx, org)
}

// MockOrganizationMemberRepository is a mock of OrganizationMemberRepository interface.
type MockOrganizationMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationMemberRepositoryMockRecorder is the mock recorder for MockOrganizationMemberRepository.
type MockOrganizationMemberRepositoryMockRecorder struct {
	mock *MockOrganizationMemberRepository
}

// NewMockOrganizationMemberRepository creates a new mock instance.
func NewMockOrganizationMemberRepository(ctrl *gomock.Controller) *MockOrganizationMemberRepository {
	mock := &MockOrganizationMemberRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationMemberRepository) EXPECT() *MockOrganizationMemberRepositoryMockRecorder {
	return m.recorder
}

// CountByOrg mocks base method.
func (m *MockOrganizationMemberRepository) CountByOrg(ctx context.Context, orgID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByOrg", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByOrg indicates an expected call of CountByOrg.
func (mr *MockOrganizationMemberRepositoryMockRecorder) CountByOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByOrg", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).CountByOrg), ctx, orgID)
}

// Create mocks base method.
func (m *MockOrganizationMemberRepository) Create(ctx context.Context, member *models.OrganizationMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationMemberRepositoryMockRecorder) Create(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).Create), ctx, member)
}

// Delete mocks base method.
func (m *MockOrganizationMemberRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationMemberRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).Delete), ctx, id)
}

// DeleteByOrgAndUser mocks base method.
func (m *MockOrganizationMemberRepository) DeleteByOrgAndUser(ctx context.Context, orgID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByOrgAndUser", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByOrgAndUser indicates an expected call of DeleteByOrgAndUser.
func (mr *MockOrganizationMemberRepositoryMockRecorder) DeleteByOrgAndUser(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByOrgAndUser", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).DeleteByOrgAndUser), ctx, orgID, userID)
}

// FindByOrgAndUser mocks base method.
func (m *MockOrganizationMemberRepository) FindByOrgAndUser(ctx context.Context, orgID, userID string) (*models.OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrgAndUser", ctx, orgID, userID)
	ret0, _ := ret[0].(*models.OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrgAndUser indicates an expected call of FindByOrgAndUser.
func (mr *MockOrganizationMemberRepositoryMockRecorder) FindByOrgAndUser(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrgAndUser", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).FindByOrgAndUser), ctx, orgID, userID)
}

// ListByOrg mocks base method.
func (m *MockOrganizationMemberRepository) ListByOrg(ctx context.Context, orgID string, opts models.MemberListOpts) ([]*models.OrganizationMember, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrg", ctx, orgID, opts)
	ret0, _ := ret[0].([]*models.OrganizationMember)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByOrg indicates an expected call of ListByOrg.
func (mr *MockOrganizationMemberRepositoryMockRecorder) ListByOrg(ctx, orgID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrg", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).ListByOrg), ctx, orgID, opts)
}

// ListByUser mocks base method.
func (m *MockOrganizationMemberRepository) ListByUser(ctx context.Context, userID string) ([]*models.OrganizationMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]*models.OrganizationMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockOrganizationMemberRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).ListByUser), ctx, userID)
}

// Update mocks base method.
func (m *MockOrganizationMemberRepository) Update(ctx context.Context, member *models.OrganizationMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationMemberRepositoryMockRecorder) Update(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationMemberRepository)(nil).Update), ctx, member)
}

// MockInvitationRepository is a mock of InvitationRepository interface.
type MockInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockInvitationRepositoryMockRecorder is the mock recorder for MockInvitationRepository.
type MockInvitationRepositoryMockRecorder struct {
	mock *MockInvitationRepository
}

// NewMockInvitationRepository creates a new mock instance.
func NewMockInvitationRepository(ctrl *gomock.Controller) *MockInvitationRepository {
	mock := &MockInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationRepository) EXPECT() *MockInvitationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvitationRepository) Create(ctx context.Context, invitation *models.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvitationRepositoryMockRecorder) Create(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockInvitationRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvitationRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvitationRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockInvitationRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockInvitationRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockInvitationRepository)(nil).DeleteExpired), ctx)
}

// FindByID mocks base method.
func (m *MockInvitationRepository) FindByID(ctx context.Context, id string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvitationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvitationRepository)(nil).FindByID), ctx, id)
}

// FindByOrgAndEmail mocks base method.
func (m *MockInvitationRepository) FindByOrgAndEmail(ctx context.Context, orgID, email string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrgAndEmail", ctx, orgID, email)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrgAndEmail indicates an expected call of FindByOrgAndEmail.
func (mr *MockInvitationRepositoryMockRecorder) FindByOrgAndEmail(ctx, orgID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrgAndEmail", reflect.TypeOf((*MockInvitationRepository)(nil).FindByOrgAndEmail), ctx, orgID, email)
}

// FindByToken mocks base method.
func (m *MockInvitationRepository) FindByToken(ctx context.Context, token string) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockInvitationRepositoryMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockInvitationRepository)(nil).FindByToken), ctx, token)
}

// ListByOrg mocks base method.
func (m *MockInvitationRepository) ListByOrg(ctx context.Context, orgID string, opts models.InvitationListOpts) ([]*models.Invitation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrg", ctx, orgID, opts)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByOrg indicates an expected call of ListByOrg.
func (mr *MockInvitationRepositoryMockRecorder) ListByOrg(ctx, orgID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrg", reflect.TypeOf((*MockInvitationRepository)(nil).ListByOrg), ctx, orgID, opts)
}

// ListPendingByEmail mocks base method.
func (m *MockInvitationRepository) ListPendingByEmail(ctx context.Context, email string) ([]*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByEmail", ctx, email)
	ret0, _ := ret[0].([]*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByEmail indicates an expected call of ListPendingByEmail.
func (mr *MockInvitationRepositoryMockRecorder) ListPendingByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByEmail", reflect.TypeOf((*MockInvitationRepository)(nil).ListPendingByEmail), ctx, email)
}

// Update mocks base method.
func (m *MockInvitationRepository) Update(ctx context.Context, invitation *models.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvitationRepositoryMockRecorder) Update(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvitationRepository)(nil).Update), ctx, invitation)
}
