// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/oauth/services (interfaces: OAuthService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_oauth_service.go -package=mocks github.com/bete7512/goauth/internal/modules/oauth/services OAuthService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/bete7512/goauth/internal/modules/oauth/services"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthService is a mock of OAuthService interface.
type MockOAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthServiceMockRecorder
	isgomock struct{}
}

// MockOAuthServiceMockRecorder is the mock recorder for MockOAuthService.
type MockOAuthServiceMockRecorder struct {
	mock *MockOAuthService
}

// NewMockOAuthService creates a new mock instance.
func NewMockOAuthService(ctrl *gomock.Controller) *MockOAuthService {
	mock := &MockOAuthService{ctrl: ctrl}
	mock.recorder = &MockOAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthService) EXPECT() *MockOAuthServiceMockRecorder {
	return m.recorder
}

// GetLinkedProviders mocks base method.
func (m *MockOAuthService) GetLinkedProviders(ctx context.Context, userID string) ([]string, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkedProviders", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetLinkedProviders indicates an expected call of GetLinkedProviders.
func (mr *MockOAuthServiceMockRecorder) GetLinkedProviders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkedProviders", reflect.TypeOf((*MockOAuthService)(nil).GetLinkedProviders), ctx, userID)
}

// HandleCallback mocks base method.
func (m *MockOAuthService) HandleCallback(ctx context.Context, providerName, code, state string, metadata *types.RequestMetadata) (*services.OAuthResult, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, providerName, code, state, metadata)
	ret0, _ := ret[0].(*services.OAuthResult)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockOAuthServiceMockRecorder) HandleCallback(ctx, providerName, code, state, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockOAuthService)(nil).HandleCallback), ctx, providerName, code, state, metadata)
}

// InitiateLogin mocks base method.
func (m *MockOAuthService) InitiateLogin(ctx context.Context, providerName, clientRedirectURI string) (string, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateLogin", ctx, providerName, clientRedirectURI)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// InitiateLogin indicates an expected call of InitiateLogin.
func (mr *MockOAuthServiceMockRecorder) InitiateLogin(ctx, providerName, clientRedirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateLogin", reflect.TypeOf((*MockOAuthService)(nil).InitiateLogin), ctx, providerName, clientRedirectURI)
}

// ListEnabledProviders mocks base method.
func (m *MockOAuthService) ListEnabledProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListEnabledProviders indicates an expected call of ListEnabledProviders.
func (mr *MockOAuthServiceMockRecorder) ListEnabledProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledProviders", reflect.TypeOf((*MockOAuthService)(nil).ListEnabledProviders))
}

// UnlinkProvider mocks base method.
func (m *MockOAuthService) UnlinkProvider(ctx context.Context, userID, providerName string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkProvider", ctx, userID, providerName)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// UnlinkProvider indicates an expected call of UnlinkProvider.
func (mr *MockOAuthServiceMockRecorder) UnlinkProvider(ctx, userID, providerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkProvider", reflect.TypeOf((*MockOAuthService)(nil).UnlinkProvider), ctx, userID, providerName)
}
