// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/csrf/services (interfaces: CSRFService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_csrf_service.go -package=mocks github.com/bete7512/goauth/internal/modules/csrf/services CSRFService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCSRFService is a mock of CSRFService interface.
type MockCSRFService struct {
	ctrl     *gomock.Controller
	recorder *MockCSRFServiceMockRecorder
	isgomock struct{}
}

// MockCSRFServiceMockRecorder is the mock recorder for MockCSRFService.
type MockCSRFServiceMockRecorder struct {
	mock *MockCSRFService
}

// NewMockCSRFService creates a new mock instance.
func NewMockCSRFService(ctrl *gomock.Controller) *MockCSRFService {
	mock := &MockCSRFService{ctrl: ctrl}
	mock.recorder = &MockCSRFServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSRFService) EXPECT() *MockCSRFServiceMockRecorder {
	return m.recorder
}

// CookieDomain mocks base method.
func (m *MockCSRFService) CookieDomain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CookieDomain")
	ret0, _ := ret[0].(string)
	return ret0
}

// CookieDomain indicates an expected call of CookieDomain.
func (mr *MockCSRFServiceMockRecorder) CookieDomain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CookieDomain", reflect.TypeOf((*MockCSRFService)(nil).CookieDomain))
}

// CookieName mocks base method.
func (m *MockCSRFService) CookieName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CookieName")
	ret0, _ := ret[0].(string)
	return ret0
}

// CookieName indicates an expected call of CookieName.
func (mr *MockCSRFServiceMockRecorder) CookieName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CookieName", reflect.TypeOf((*MockCSRFService)(nil).CookieName))
}

// CookiePath mocks base method.
func (m *MockCSRFService) CookiePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CookiePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// CookiePath indicates an expected call of CookiePath.
func (mr *MockCSRFServiceMockRecorder) CookiePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CookiePath", reflect.TypeOf((*MockCSRFService)(nil).CookiePath))
}

// FormFieldName mocks base method.
func (m *MockCSRFService) FormFieldName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormFieldName")
	ret0, _ := ret[0].(string)
	return ret0
}

// FormFieldName indicates an expected call of FormFieldName.
func (mr *MockCSRFServiceMockRecorder) FormFieldName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormFieldName", reflect.TypeOf((*MockCSRFService)(nil).FormFieldName))
}

// GenerateToken mocks base method.
func (m *MockCSRFService) GenerateToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockCSRFServiceMockRecorder) GenerateToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockCSRFService)(nil).GenerateToken))
}

// HeaderName mocks base method.
func (m *MockCSRFService) HeaderName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderName")
	ret0, _ := ret[0].(string)
	return ret0
}

// HeaderName indicates an expected call of HeaderName.
func (mr *MockCSRFServiceMockRecorder) HeaderName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderName", reflect.TypeOf((*MockCSRFService)(nil).HeaderName))
}

// TokenExpiry mocks base method.
func (m *MockCSRFService) TokenExpiry() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenExpiry")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TokenExpiry indicates an expected call of TokenExpiry.
func (mr *MockCSRFServiceMockRecorder) TokenExpiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenExpiry", reflect.TypeOf((*MockCSRFService)(nil).TokenExpiry))
}

// TokensMatch mocks base method.
func (m *MockCSRFService) TokensMatch(a, b string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokensMatch", a, b)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TokensMatch indicates an expected call of TokensMatch.
func (mr *MockCSRFServiceMockRecorder) TokensMatch(a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokensMatch", reflect.TypeOf((*MockCSRFService)(nil).TokensMatch), a, b)
}

// ValidateToken mocks base method.
func (m *MockCSRFService) ValidateToken(token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockCSRFServiceMockRecorder) ValidateToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockCSRFService)(nil).ValidateToken), token)
}
