// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/core/services (interfaces: CoreService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_core_service.go -package=mocks github.com/bete7512/goauth/internal/modules/core/services CoreService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/bete7512/goauth/internal/modules/core/handlers/dto"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockCoreService is a mock of CoreService interface.
type MockCoreService struct {
	ctrl     *gomock.Controller
	recorder *MockCoreServiceMockRecorder
	isgomock struct{}
}

// MockCoreServiceMockRecorder is the mock recorder for MockCoreService.
type MockCoreServiceMockRecorder struct {
	mock *MockCoreService
}

// NewMockCoreService creates a new mock instance.
func NewMockCoreService(ctrl *gomock.Controller) *MockCoreService {
	mock := &MockCoreService{ctrl: ctrl}
	mock.recorder = &MockCoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreService) EXPECT() *MockCoreServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockCoreService) ChangePassword(ctx context.Context, userID string, req *dto.ChangePasswordRequest) (*dto.MessageResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, req)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockCoreServiceMockRecorder) ChangePassword(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockCoreService)(nil).ChangePassword), ctx, userID, req)
}

// CheckEmailAvailability mocks base method.
func (m *MockCoreService) CheckEmailAvailability(ctx context.Context, email string) (*dto.CheckAvailabilityResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailAvailability", ctx, email)
	ret0, _ := ret[0].(*dto.CheckAvailabilityResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// CheckEmailAvailability indicates an expected call of CheckEmailAvailability.
func (mr *MockCoreServiceMockRecorder) CheckEmailAvailability(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailAvailability", reflect.TypeOf((*MockCoreService)(nil).CheckEmailAvailability), ctx, email)
}

// CheckPhoneAvailability mocks base method.
func (m *MockCoreService) CheckPhoneAvailability(ctx context.Context, phone string) (*dto.CheckAvailabilityResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPhoneAvailability", ctx, phone)
	ret0, _ := ret[0].(*dto.CheckAvailabilityResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// CheckPhoneAvailability indicates an expected call of CheckPhoneAvailability.
func (mr *MockCoreServiceMockRecorder) CheckPhoneAvailability(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPhoneAvailability", reflect.TypeOf((*MockCoreService)(nil).CheckPhoneAvailability), ctx, phone)
}

// CheckUsernameAvailability mocks base method.
func (m *MockCoreService) CheckUsernameAvailability(ctx context.Context, username string) (*dto.CheckAvailabilityResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUsernameAvailability", ctx, username)
	ret0, _ := ret[0].(*dto.CheckAvailabilityResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// CheckUsernameAvailability indicates an expected call of CheckUsernameAvailability.
func (mr *MockCoreServiceMockRecorder) CheckUsernameAvailability(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUsernameAvailability", reflect.TypeOf((*MockCoreService)(nil).CheckUsernameAvailability), ctx, username)
}

// ForgotPassword mocks base method.
func (m *MockCoreService) ForgotPassword(ctx context.Context, req *dto.ForgotPasswordRequest) (*dto.MessageResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockCoreServiceMockRecorder) ForgotPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockCoreService)(nil).ForgotPassword), ctx, req)
}

// GetCurrentUser mocks base method.
func (m *MockCoreService) GetCurrentUser(ctx context.Context, userID string) (*dto.UserDTO, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx, userID)
	ret0, _ := ret[0].(*dto.UserDTO)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockCoreServiceMockRecorder) GetCurrentUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockCoreService)(nil).GetCurrentUser), ctx, userID)
}

// GetProfile mocks base method.
func (m *MockCoreService) GetProfile(ctx context.Context, userID string) (*dto.UserDTO, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*dto.UserDTO)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockCoreServiceMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockCoreService)(nil).GetProfile), ctx, userID)
}

// ResetPassword mocks base method.
func (m *MockCoreService) ResetPassword(ctx context.Context, req *dto.ResetPasswordRequest) (*dto.MessageResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(*dto.MessageResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockCoreServiceMockRecorder) ResetPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockCoreService)(nil).ResetPassword), ctx, req)
}

// Signup mocks base method.
func (m *MockCoreService) Signup(ctx context.Context, req *dto.SignupRequest) (*dto.AuthResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, req)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockCoreServiceMockRecorder) Signup(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockCoreService)(nil).Signup), ctx, req)
}

// UpdateProfile mocks base method.
func (m *MockCoreService) UpdateProfile(ctx context.Context, userID string, req *dto.UpdateProfileRequest) (*dto.UserDTO, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, req)
	ret0, _ := ret[0].(*dto.UserDTO)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockCoreServiceMockRecorder) UpdateProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockCoreService)(nil).UpdateProfile), ctx, userID, req)
}
