// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/oauth/providers (interfaces: OAuthProvider)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_oauth_provider.go -package=mocks github.com/bete7512/goauth/internal/modules/oauth/providers OAuthProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	providers "github.com/bete7512/goauth/internal/modules/oauth/providers"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuthProvider is a mock of OAuthProvider interface.
type MockOAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthProviderMockRecorder
	isgomock struct{}
}

// MockOAuthProviderMockRecorder is the mock recorder for MockOAuthProvider.
type MockOAuthProviderMockRecorder struct {
	mock *MockOAuthProvider
}

// NewMockOAuthProvider creates a new mock instance.
func NewMockOAuthProvider(ctrl *gomock.Controller) *MockOAuthProvider {
	mock := &MockOAuthProvider{ctrl: ctrl}
	mock.recorder = &MockOAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthProvider) EXPECT() *MockOAuthProviderMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockOAuthProvider) AuthCodeURL(state string, opts providers.AuthCodeURLOptions) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state, opts)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockOAuthProviderMockRecorder) AuthCodeURL(state, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockOAuthProvider)(nil).AuthCodeURL), state, opts)
}

// Exchange mocks base method.
func (m *MockOAuthProvider) Exchange(ctx context.Context, code string, opts providers.ExchangeOptions) (*providers.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, code, opts)
	ret0, _ := ret[0].(*providers.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockOAuthProviderMockRecorder) Exchange(ctx, code, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockOAuthProvider)(nil).Exchange), ctx, code, opts)
}

// Name mocks base method.
func (m *MockOAuthProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockOAuthProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockOAuthProvider)(nil).Name))
}

// SupportsOIDC mocks base method.
func (m *MockOAuthProvider) SupportsOIDC() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsOIDC")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsOIDC indicates an expected call of SupportsOIDC.
func (mr *MockOAuthProviderMockRecorder) SupportsOIDC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsOIDC", reflect.TypeOf((*MockOAuthProvider)(nil).SupportsOIDC))
}

// UserInfo mocks base method.
func (m *MockOAuthProvider) UserInfo(ctx context.Context, accessToken string) (*providers.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserInfo", ctx, accessToken)
	ret0, _ := ret[0].(*providers.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserInfo indicates an expected call of UserInfo.
func (mr *MockOAuthProviderMockRecorder) UserInfo(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserInfo", reflect.TypeOf((*MockOAuthProvider)(nil).UserInfo), ctx, accessToken)
}

// ValidateIDToken mocks base method.
func (m *MockOAuthProvider) ValidateIDToken(ctx context.Context, idToken string) (*providers.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateIDToken", ctx, idToken)
	ret0, _ := ret[0].(*providers.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateIDToken indicates an expected call of ValidateIDToken.
func (mr *MockOAuthProviderMockRecorder) ValidateIDToken(ctx, idToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateIDToken", reflect.TypeOf((*MockOAuthProvider)(nil).ValidateIDToken), ctx, idToken)
}
