// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/models (interfaces: VerificationTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_verification_repository.go -package=mocks github.com/bete7512/goauth/pkg/models VerificationTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationTokenRepository is a mock of VerificationTokenRepository interface.
type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenRepositoryMockRecorder is the mock recorder for MockVerificationTokenRepository.
type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

// NewMockVerificationTokenRepository creates a new mock instance.
func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerificationTokenRepository) Create(ctx context.Context, token *models.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Create), ctx, token)
}

// Delete mocks base method.
func (m *MockVerificationTokenRepository) Delete(ctx context.Context, id, tokenType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, tokenType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerificationTokenRepositoryMockRecorder) Delete(ctx, id, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Delete), ctx, id, tokenType)
}

// DeleteExpired mocks base method.
func (m *MockVerificationTokenRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockVerificationTokenRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockVerificationTokenRepository)(nil).DeleteExpired), ctx)
}

// FindByCode mocks base method.
func (m *MockVerificationTokenRepository) FindByCode(ctx context.Context, code, tokenType string) (*models.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code, tokenType)
	ret0, _ := ret[0].(*models.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindByCode(ctx, code, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindByCode), ctx, code, tokenType)
}

// FindByEmailAndType mocks base method.
func (m *MockVerificationTokenRepository) FindByEmailAndType(ctx context.Context, email, tokenType string) (*models.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailAndType", ctx, email, tokenType)
	ret0, _ := ret[0].(*models.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailAndType indicates an expected call of FindByEmailAndType.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindByEmailAndType(ctx, email, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailAndType", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindByEmailAndType), ctx, email, tokenType)
}

// FindByPhoneAndType mocks base method.
func (m *MockVerificationTokenRepository) FindByPhoneAndType(ctx context.Context, phone, tokenType string) (*models.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPhoneAndType", ctx, phone, tokenType)
	ret0, _ := ret[0].(*models.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPhoneAndType indicates an expected call of FindByPhoneAndType.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindByPhoneAndType(ctx, phone, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPhoneAndType", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindByPhoneAndType), ctx, phone, tokenType)
}

// FindByToken mocks base method.
func (m *MockVerificationTokenRepository) FindByToken(ctx context.Context, token string) (*models.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*models.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindByToken), ctx, token)
}

// MarkAsUsed mocks base method.
func (m *MockVerificationTokenRepository) MarkAsUsed(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockVerificationTokenRepositoryMockRecorder) MarkAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockVerificationTokenRepository)(nil).MarkAsUsed), ctx, id)
}
