// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/types (interfaces: EventBus,AsyncBackend)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_events.go -package=mocks github.com/bete7512/goauth/pkg/types EventBus,AsyncBackend
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEventBus is a mock of EventBus interface.
type MockEventBus struct {
	ctrl     *gomock.Controller
	recorder *MockEventBusMockRecorder
	isgomock struct{}
}

// MockEventBusMockRecorder is the mock recorder for MockEventBus.
type MockEventBusMockRecorder struct {
	mock *MockEventBus
}

// NewMockEventBus creates a new mock instance.
func NewMockEventBus(ctrl *gomock.Controller) *MockEventBus {
	mock := &MockEventBus{ctrl: ctrl}
	mock.recorder = &MockEventBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventBus) EXPECT() *MockEventBusMockRecorder {
	return m.recorder
}

// EmitAsync mocks base method.
func (m *MockEventBus) EmitAsync(ctx context.Context, eventType types.EventType, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitAsync", ctx, eventType, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitAsync indicates an expected call of EmitAsync.
func (mr *MockEventBusMockRecorder) EmitAsync(ctx, eventType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitAsync", reflect.TypeOf((*MockEventBus)(nil).EmitAsync), ctx, eventType, data)
}

// EmitSync mocks base method.
func (m *MockEventBus) EmitSync(ctx context.Context, eventType types.EventType, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitSync", ctx, eventType, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitSync indicates an expected call of EmitSync.
func (mr *MockEventBusMockRecorder) EmitSync(ctx, eventType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitSync", reflect.TypeOf((*MockEventBus)(nil).EmitSync), ctx, eventType, data)
}

// Subscribe mocks base method.
func (m *MockEventBus) Subscribe(eventType types.EventType, handler types.EventHandler, opts ...any) {
	m.ctrl.T.Helper()
	varargs := []any{eventType, handler}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Subscribe", varargs...)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventBusMockRecorder) Subscribe(eventType, handler any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{eventType, handler}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventBus)(nil).Subscribe), varargs...)
}

// MockAsyncBackend is a mock of AsyncBackend interface.
type MockAsyncBackend struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncBackendMockRecorder
	isgomock struct{}
}

// MockAsyncBackendMockRecorder is the mock recorder for MockAsyncBackend.
type MockAsyncBackendMockRecorder struct {
	mock *MockAsyncBackend
}

// NewMockAsyncBackend creates a new mock instance.
func NewMockAsyncBackend(ctrl *gomock.Controller) *MockAsyncBackend {
	mock := &MockAsyncBackend{ctrl: ctrl}
	mock.recorder = &MockAsyncBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncBackend) EXPECT() *MockAsyncBackendMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAsyncBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAsyncBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAsyncBackend)(nil).Close))
}

// Name mocks base method.
func (m *MockAsyncBackend) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAsyncBackendMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAsyncBackend)(nil).Name))
}

// Publish mocks base method.
func (m *MockAsyncBackend) Publish(ctx context.Context, eventType types.EventType, event *types.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, eventType, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockAsyncBackendMockRecorder) Publish(ctx, eventType, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAsyncBackend)(nil).Publish), ctx, eventType, event)
}

// Subscribe mocks base method.
func (m *MockAsyncBackend) Subscribe(ctx context.Context, dispatcher types.EventDispatcher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, dispatcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockAsyncBackendMockRecorder) Subscribe(ctx, dispatcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockAsyncBackend)(nil).Subscribe), ctx, dispatcher)
}
