// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/notification/models (interfaces: EmailSender,SMSSender)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_email_sender.go -package=mocks github.com/bete7512/goauth/internal/modules/notification/models EmailSender,SMSSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/goauth/internal/modules/notification/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailSender) SendEmail(ctx context.Context, message *models.EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailSenderMockRecorder) SendEmail(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailSender)(nil).SendEmail), ctx, message)
}

// VerifyConfig mocks base method.
func (m *MockEmailSender) VerifyConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyConfig indicates an expected call of VerifyConfig.
func (mr *MockEmailSenderMockRecorder) VerifyConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyConfig", reflect.TypeOf((*MockEmailSender)(nil).VerifyConfig), ctx)
}

// MockSMSSender is a mock of SMSSender interface.
type MockSMSSender struct {
	ctrl     *gomock.Controller
	recorder *MockSMSSenderMockRecorder
	isgomock struct{}
}

// MockSMSSenderMockRecorder is the mock recorder for MockSMSSender.
type MockSMSSenderMockRecorder struct {
	mock *MockSMSSender
}

// NewMockSMSSender creates a new mock instance.
func NewMockSMSSender(ctrl *gomock.Controller) *MockSMSSender {
	mock := &MockSMSSender{ctrl: ctrl}
	mock.recorder = &MockSMSSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMSSender) EXPECT() *MockSMSSenderMockRecorder {
	return m.recorder
}

// SendSMS mocks base method.
func (m *MockSMSSender) SendSMS(ctx context.Context, message *models.SMSMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSMS", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSMS indicates an expected call of SendSMS.
func (mr *MockSMSSenderMockRecorder) SendSMS(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSMS", reflect.TypeOf((*MockSMSSender)(nil).SendSMS), ctx, message)
}

// VerifyConfig mocks base method.
func (m *MockSMSSender) VerifyConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyConfig indicates an expected call of VerifyConfig.
func (mr *MockSMSSenderMockRecorder) VerifyConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyConfig", reflect.TypeOf((*MockSMSSender)(nil).VerifyConfig), ctx)
}
