// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/internal/modules/session/services (interfaces: SessionService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_session_service.go -package=mocks github.com/bete7512/goauth/internal/modules/session/services SessionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/bete7512/goauth/internal/modules/session/handlers/dto"
	models "github.com/bete7512/goauth/pkg/models"
	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// DeleteAllSessions mocks base method.
func (m *MockSessionService) DeleteAllSessions(ctx context.Context, userID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllSessions", ctx, userID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// DeleteAllSessions indicates an expected call of DeleteAllSessions.
func (mr *MockSessionServiceMockRecorder) DeleteAllSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllSessions", reflect.TypeOf((*MockSessionService)(nil).DeleteAllSessions), ctx, userID)
}

// DeleteSession mocks base method.
func (m *MockSessionService) DeleteSession(ctx context.Context, userID, sessionID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionServiceMockRecorder) DeleteSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionService)(nil).DeleteSession), ctx, userID, sessionID)
}

// FindSessionByToken mocks base method.
func (m *MockSessionService) FindSessionByToken(ctx context.Context, token string) (*models.Session, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionByToken", ctx, token)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// FindSessionByToken indicates an expected call of FindSessionByToken.
func (mr *MockSessionServiceMockRecorder) FindSessionByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionByToken", reflect.TypeOf((*MockSessionService)(nil).FindSessionByToken), ctx, token)
}

// GetSession mocks base method.
func (m *MockSessionService) GetSession(ctx context.Context, userID, sessionID string) (*dto.SessionDTO, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(*dto.SessionDTO)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionServiceMockRecorder) GetSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionService)(nil).GetSession), ctx, userID, sessionID)
}

// ListSessions mocks base method.
func (m *MockSessionService) ListSessions(ctx context.Context, userID, currentSessionID string, opts models.SessionListOpts) ([]dto.SessionDTO, int64, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, userID, currentSessionID, opts)
	ret0, _ := ret[0].([]dto.SessionDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(*types.GoAuthError)
	return ret0, ret1, ret2
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockSessionServiceMockRecorder) ListSessions(ctx, userID, currentSessionID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockSessionService)(nil).ListSessions), ctx, userID, currentSessionID, opts)
}

// Login mocks base method.
func (m *MockSessionService) Login(ctx context.Context, req *dto.LoginRequest, metadata *types.RequestMetadata) (dto.AuthResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, metadata)
	ret0, _ := ret[0].(dto.AuthResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockSessionServiceMockRecorder) Login(ctx, req, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockSessionService)(nil).Login), ctx, req, metadata)
}

// Logout mocks base method.
func (m *MockSessionService) Logout(ctx context.Context, userID, sessionID string) *types.GoAuthError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, userID, sessionID)
	ret0, _ := ret[0].(*types.GoAuthError)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockSessionServiceMockRecorder) Logout(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockSessionService)(nil).Logout), ctx, userID, sessionID)
}

// Refresh mocks base method.
func (m *MockSessionService) Refresh(ctx context.Context, req *dto.RefreshRequest) (dto.AuthResponse, *types.GoAuthError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, req)
	ret0, _ := ret[0].(dto.AuthResponse)
	ret1, _ := ret[1].(*types.GoAuthError)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockSessionServiceMockRecorder) Refresh(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockSessionService)(nil).Refresh), ctx, req)
}
