// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/goauth/pkg/types (interfaces: AuthInterceptorRegistry)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/mocks/mock_interceptor.go -package=mocks github.com/bete7512/goauth/pkg/types AuthInterceptorRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/bete7512/goauth/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthInterceptorRegistry is a mock of AuthInterceptorRegistry interface.
type MockAuthInterceptorRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInterceptorRegistryMockRecorder
	isgomock struct{}
}

// MockAuthInterceptorRegistryMockRecorder is the mock recorder for MockAuthInterceptorRegistry.
type MockAuthInterceptorRegistryMockRecorder struct {
	mock *MockAuthInterceptorRegistry
}

// NewMockAuthInterceptorRegistry creates a new mock instance.
func NewMockAuthInterceptorRegistry(ctrl *gomock.Controller) *MockAuthInterceptorRegistry {
	mock := &MockAuthInterceptorRegistry{ctrl: ctrl}
	mock.recorder = &MockAuthInterceptorRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInterceptorRegistry) EXPECT() *MockAuthInterceptorRegistryMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAuthInterceptorRegistry) Register(name string, interceptor types.AuthInterceptor, priority int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", name, interceptor, priority)
}

// Register indicates an expected call of Register.
func (mr *MockAuthInterceptorRegistryMockRecorder) Register(name, interceptor, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthInterceptorRegistry)(nil).Register), name, interceptor, priority)
}

// Run mocks base method.
func (m *MockAuthInterceptorRegistry) Run(ctx context.Context, params *types.InterceptParams) (map[string]any, []types.LoginChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, params)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].([]types.LoginChallenge)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Run indicates an expected call of Run.
func (mr *MockAuthInterceptorRegistryMockRecorder) Run(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAuthInterceptorRegistry)(nil).Run), ctx, params)
}
